export const data = {
  text: [
    "Assumiu o lugar de fala da ancestralidade da homoafetividade para propagar inverdades. Abusou psicologicamente das pautas minoritárias ressignificando a conversa com inverdades.",

    "Transversalizou as palavras dos pretos, pardos, miscigenados, indígenas e autoproclamados se aproveitando da apropriação cultural, transversalizou as palavras da reparação histórica há tanto tempo necessária de maneira a dizimar o discurso acolhedor. Usurpou o lugar de fala de seus iguais, silenciados pela heteronormatividade patriarcal ressignificando a conversa com inverdades.",

    "Reduziu o discurso da mulher fenotipicamente negra fingindo não entender o contexto sócio-cultural, estereotipou a biologia da mulher branca socialmente privilegiada, em detrimento da pauta antirracial para proveito proprio. Usurpou o lugar de fala das mulheres trans dos gays e não-binários.",

    "Abusou psicologicamente da mulher branca socialmente privilegiada, em detrimento da pauta antirracial se aproveitando da apropriação cultural, promoveu a deslegitimação das pautas minoritárias perpetuando o fascismo. Diminutizou as lamúrias das pautas minoritárias se aproveitando da apropriação cultural.",

    "Desrespeitou a jornada do homem negro convocado ao desejo de se autosabotar para proveito proprio, recusou internalizar as diversidades da homoafetividade dos gays e não-binários, ofendeu as vulnerabilidades dos pretos, pardos, miscigenados, indígenas e autoproclamados perpetuando o fascismo. Desalinhou as pautas da homoafetividade para proveito proprio.",

    "Julgou o caráter da luta anti-colonialista de maneira a dizimar o discurso acolhedor. Reduziu o discurso da reparação histórica há tanto tempo necessária perpetuando o fascismo. Julgou o caráter dos pretos, pardos, miscigenados, indígenas e autoproclamados se aproveitando de uma pauta coletiva para resolver um B.O que é seu.",

    "Quizsfazer palco em cima de seus iguais, silenciados pela heteronormatividade patriarcal para propagar inverdades, julgou o caráter da reparação histórica há tanto tempo necessária sendo contraproducente com quem é diferente de você. Desalinhou as pautas dos indivíduos silenciados por seus lugares de dores se aproveitando da apropriação cultural. Desalinhou as pautas da luta anti-colonialista sendo contraproducente com quem é diferente de você, descontextualizou a argumentatividade da luta anti-colonialista sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora.",

    "Incentivou a erradicação de seus iguais, silenciados pela heteronormatividade patriarcal com o intuito egoístico que transcendem a normalidade dos fatos. Se apropriou da luta anti-colonialista infligindo sentimentos de dor na alma dos menos privilegiados, ressignificou inverdades da mulher branca socialmente privilegiada, em detrimento da pauta antirracial para propagar inverdades. Desrespeitou a jornada da luta anti-colonialista se aproveitando de uma pauta coletiva para resolver um B.O que é seu, desrespeitou a jornada da mulher fenotipicamente negra para proveito proprio.",

    "Descontextualizou a argumentatividade da reparação histórica há tanto tempo necessária se aproveitando da apropriação cultural. Quizsfazer palco em cima da homoafetividade fingindo não entender o contexto sócio-cultural. Corrompeu as descontruções da mulher fenotipicamente negra se aproveitando de uma pauta coletiva para resolver um B.O que é seu.",

    "Recusou internalizar as diversidades da luta anti-colonialista perpetuando o fascismo. Se aproveitou da mulher fenotipicamente negra se aproveitando da apropriação cultural, se apropriou das pautas minoritárias de maneira a dizimar o discurso acolhedor.",

    "Alvejou a militância das pautas minoritárias com o intuito egoístico que transcendem a normalidade dos fatos. Transversalizou as palavras da mulher branca socialmente privilegiada, em detrimento da pauta antirracial se aproveitando de uma pauta coletiva para resolver um B.O que é seu.",

    "Diminutizou as lamúrias da homoafetividade perpetuando o fascismo. Promoveu a deslegitimação da comunidade LGBTQIA+ no contexto civilizacional contemporâneo sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora, diminutizou as lamúrias da reparação histórica há tanto tempo necessária perpetuando o fascismo. Ressignificou inverdades da mulher branca socialmente privilegiada, em detrimento da pauta antirracial ressignificando a conversa com inverdades.",

    "Prestou desacolhimento da mulher branca socialmente privilegiada, em detrimento da pauta antirracial ressignificando a conversa com inverdades. Deslegitimou a relativação da comunidade LGBTQIA+ no contexto civilizacional contemporâneo infligindo sentimentos de dor na alma dos menos privilegiados, deslegitimou a relativação da mulher branca socialmente privilegiada, em detrimento da pauta antirracial se aproveitando de uma pauta coletiva para resolver um B.O que é seu. Julgou o caráter dos indivíduos silenciados por seus lugares de dores dos gays e não-binários, descontextualizou a argumentatividade da mulher fenotipicamente negra com o intuito egoístico que transcendem a normalidade dos fatos, reduziu o discurso do homem negro convocado ao desejo de se autosabotar se aproveitando de uma pauta coletiva para resolver um B.O que é seu.",

    "Desestabilizou as oportunidades de seus iguais, silenciados pela heteronormatividade patriarcal dos gays e não-binários. Diminutizou as lamúrias da luta anti-colonialista fingindo não entender o contexto sócio-cultural. Estereotipou a biologia da comunidade LGBTQIA+ no contexto civilizacional contemporâneo fingindo não entender o contexto sócio-cultural, desestabilizou as oportunidades da comunidade LGBTQIA+ no contexto civilizacional contemporâneo ressignificando a conversa com inverdades.",

    "Se aproveitou da luta anti-colonialista sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora. Estereotipou a biologia das pautas minoritárias fingindo não entender o contexto sócio-cultural.",

    "Ofendeu as vulnerabilidades dos pretos, pardos, miscigenados, indígenas e autoproclamados para proveito proprio. Incentivou a erradicação do homem negro convocado ao desejo de se autosabotar se aproveitando de uma pauta coletiva para resolver um B.O que é seu, criticou maliciosamente os principios das pautas minoritárias sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora.",

    "Assumiu o lugar de fala da ancestralidade de seus iguais, silenciados pela heteronormatividade patriarcal dos gays e não-binários. Criticou maliciosamente os principios da comunidade LGBTQIA+ no contexto civilizacional contemporâneo perpetuando o fascismo.",

    "Desmobilizou os discursos de seus iguais, silenciados pela heteronormatividade patriarcal infligindo sentimentos de dor na alma dos menos privilegiados. Corrompeu as descontruções da reparação histórica há tanto tempo necessária cujos fenótipos nunca serão sobrepujados em detrimento dos negros, promoveu a deslegitimação da mulher branca socialmente privilegiada, em detrimento da pauta antirracial ressignificando a conversa com inverdades. Prestou desacolhimento das pautas minoritárias dos gays e não-binários.",

    "Corrompeu as descontruções da mulher branca socialmente privilegiada, em detrimento da pauta antirracial dos gays e não-binários. Incentivou a erradicação das pautas minoritárias de maneira a dizimar o discurso acolhedor, prestou desacolhimento da reparação histórica há tanto tempo necessária se aproveitando de uma pauta coletiva para resolver um B.O que é seu.",

    "Diminutizou as lamúrias de seus iguais, silenciados pela heteronormatividade patriarcal com o intuito egoístico que transcendem a normalidade dos fatos. Diminutizou as lamúrias das pautas minoritárias para proveito proprio. Ressignificou inverdades das mulheres trans ressignificando a conversa com inverdades.",

    "Se aproveitou do discurso dos pretos, pardos, miscigenados, indígenas e autoproclamados infligindo sentimentos de dor na alma dos menos privilegiados. Reduziu o discurso do homem negro convocado ao desejo de se autosabotar cujos fenótipos nunca serão sobrepujados em detrimento dos negros, se aproveitou do discurso das pautas minoritárias infligindo sentimentos de dor na alma dos menos privilegiados.",

    "Descentralizou as uniformidades do discurso dos pretos, pardos, miscigenados, indígenas e autoproclamados fingindo não entender o contexto sócio-cultural, descontextualizou a argumentatividade do homem negro convocado ao desejo de se autosabotar sendo contraproducente com quem é diferente de você. Criticou maliciosamente os principios da mulher branca socialmente privilegiada, em detrimento da pauta antirracial perpetuando o fascismo, estereotipou a biologia dos pretos, pardos, miscigenados, indígenas e autoproclamados fingindo não entender o contexto sócio-cultural. Assumiu o lugar de fala da ancestralidade de seus iguais, silenciados pela heteronormatividade patriarcal infligindo sentimentos de dor na alma dos menos privilegiados.",

    "Reduziu o discurso do homem negro convocado ao desejo de se autosabotar cujos fenótipos nunca serão sobrepujados em detrimento dos negros. Enfraqueceu as conquistas dos pretos, pardos, miscigenados, indígenas e autoproclamados cujos fenótipos nunca serão sobrepujados em detrimento dos negros.",

    "Alvejou a militância da luta anti-colonialista dos gays e não-binários. Se aproveitou do discurso dos indivíduos silenciados por seus lugares de dores se aproveitando de uma pauta coletiva para resolver um B.O que é seu.",

    "Quizsfazer palco em cima da luta anti-colonialista ressignificando a conversa com inverdades. Promoveu a deslegitimação da luta anti-colonialista cujos fenótipos nunca serão sobrepujados em detrimento dos negros. Quizsfazer palco em cima de seus iguais, silenciados pela heteronormatividade patriarcal sendo contraproducente com quem é diferente de você.",

    "Promoveu a deslegitimação das pautas minoritárias de maneira a dizimar o discurso acolhedor. Alvejou a militância da comunidade LGBTQIA+ no contexto civilizacional contemporâneo se aproveitando da apropriação cultural, ressignificou inverdades dos indivíduos silenciados por seus lugares de dores se aproveitando de uma pauta coletiva para resolver um B.O que é seu, desrespeitou a jornada das pautas minoritárias cujos fenótipos nunca serão sobrepujados em detrimento dos negros, estereotipou a biologia do homem negro convocado ao desejo de se autosabotar dos gays e não-binários. Reduziu o discurso dos indivíduos silenciados por seus lugares de dores de maneira a dizimar o discurso acolhedor.",

    "Alvejou a militância da reparação histórica há tanto tempo necessária infligindo sentimentos de dor na alma dos menos privilegiados. Incentivou a erradicação das pautas minoritárias infligindo sentimentos de dor na alma dos menos privilegiados, desalinhou as pautas dos indivíduos silenciados por seus lugares de dores perpetuando o fascismo, ofendeu as vulnerabilidades dos indivíduos silenciados por seus lugares de dores com o intuito egoístico que transcendem a normalidade dos fatos.",

    "Transversalizou as palavras do homem negro convocado ao desejo de se autosabotar ressignificando a conversa com inverdades. Julgou o caráter de seus iguais, silenciados pela heteronormatividade patriarcal com o intuito egoístico que transcendem a normalidade dos fatos. Incentivou a erradicação da mulher branca socialmente privilegiada, em detrimento da pauta antirracial cujos fenótipos nunca serão sobrepujados em detrimento dos negros.",

    "Desmobilizou os discursos dos pretos, pardos, miscigenados, indígenas e autoproclamados cujos fenótipos nunca serão sobrepujados em detrimento dos negros, descentralizou as uniformidades do discurso da luta anti-colonialista sendo contraproducente com quem é diferente de você, ressignificou inverdades dos indivíduos silenciados por seus lugares de dores perpetuando o fascismo. Transversalizou as palavras da homoafetividade infligindo sentimentos de dor na alma dos menos privilegiados.",

    "Usurpou o lugar de fala de seus iguais, silenciados pela heteronormatividade patriarcal cujos fenótipos nunca serão sobrepujados em detrimento dos negros. Potencializou o silenciamento da reparação histórica há tanto tempo necessária perpetuando o fascismo, ofendeu as vulnerabilidades da mulher branca socialmente privilegiada, em detrimento da pauta antirracial para propagar inverdades, desrespeitou a jornada do homem negro convocado ao desejo de se autosabotar para propagar inverdades, descontextualizou a argumentatividade da mulher branca socialmente privilegiada, em detrimento da pauta antirracial ressignificando a conversa com inverdades. Julgou o caráter da homoafetividade para propagar inverdades.",

    "Abusou psicologicamente da comunidade LGBTQIA+ no contexto civilizacional contemporâneo dos gays e não-binários. Se aproveitou do discurso das pautas minoritárias perpetuando o fascismo, potencializou o silenciamento da mulher branca socialmente privilegiada, em detrimento da pauta antirracial se aproveitando da apropriação cultural.",

    "Transversalizou as palavras da mulher fenotipicamente negra para propagar inverdades, potencializou o silenciamento das mulheres trans se aproveitando de uma pauta coletiva para resolver um B.O que é seu, criticou maliciosamente os principios dos indivíduos silenciados por seus lugares de dores fingindo não entender o contexto sócio-cultural. Diminutizou as lamúrias do homem negro convocado ao desejo de se autosabotar sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora. Descontextualizou a argumentatividade de seus iguais, silenciados pela heteronormatividade patriarcal dos gays e não-binários, diminutizou as lamúrias da comunidade LGBTQIA+ no contexto civilizacional contemporâneo sendo contraproducente com quem é diferente de você.",

    "Corrompeu as descontruções da comunidade LGBTQIA+ no contexto civilizacional contemporâneo para proveito proprio, usurpou o lugar de fala da homoafetividade infligindo sentimentos de dor na alma dos menos privilegiados, promoveu a deslegitimação da reparação histórica há tanto tempo necessária ressignificando a conversa com inverdades, potencializou o silenciamento dos indivíduos silenciados por seus lugares de dores de maneira a dizimar o discurso acolhedor. Incentivou a erradicação dos indivíduos silenciados por seus lugares de dores sendo contraproducente com quem é diferente de você.",

    "Se aproveitou do discurso das mulheres trans para proveito proprio, se aproveitou do discurso das mulheres trans sendo contraproducente com quem é diferente de você. Diminutizou as lamúrias da comunidade LGBTQIA+ no contexto civilizacional contemporâneo se aproveitando de uma pauta coletiva para resolver um B.O que é seu.",

    "Abusou psicologicamente da homoafetividade sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora, assumiu o lugar de fala da ancestralidade da luta anti-colonialista fingindo não entender o contexto sócio-cultural. Usurpou o lugar de fala da mulher branca socialmente privilegiada, em detrimento da pauta antirracial fingindo não entender o contexto sócio-cultural.",

    "Desrespeitou a jornada da comunidade LGBTQIA+ no contexto civilizacional contemporâneo dos gays e não-binários. Corrompeu as descontruções da mulher fenotipicamente negra sendo contraproducente com quem é diferente de você, se apropriou da homoafetividade se aproveitando de uma pauta coletiva para resolver um B.O que é seu.",

    "Desmobilizou os discursos das mulheres trans se aproveitando da apropriação cultural. Usurpou o lugar de fala das pautas minoritárias dos gays e não-binários. Corrompeu as descontruções da comunidade LGBTQIA+ no contexto civilizacional contemporâneo cujos fenótipos nunca serão sobrepujados em detrimento dos negros.",

    "Deslegitimou a relativação da homoafetividade cujos fenótipos nunca serão sobrepujados em detrimento dos negros. Tirou o contexto da reparação histórica há tanto tempo necessária dos gays e não-binários, se apropriou de seus iguais, silenciados pela heteronormatividade patriarcal se aproveitando da apropriação cultural.",

    "Se aproveitou do discurso da luta anti-colonialista para proveito proprio. Corrompeu as descontruções da comunidade LGBTQIA+ no contexto civilizacional contemporâneo ressignificando a conversa com inverdades.",

    "Se aproveitou da luta anti-colonialista ressignificando a conversa com inverdades. Desalinhou as pautas da mulher fenotipicamente negra para propagar inverdades, ofendeu as vulnerabilidades da comunidade LGBTQIA+ no contexto civilizacional contemporâneo para propagar inverdades. Usurpou o lugar de fala do homem negro convocado ao desejo de se autosabotar fingindo não entender o contexto sócio-cultural, potencializou o silenciamento das pautas minoritárias dos gays e não-binários.",

    "Quizsfazer palco em cima de seus iguais, silenciados pela heteronormatividade patriarcal com o intuito egoístico que transcendem a normalidade dos fatos, criticou maliciosamente os principios das mulheres trans para propagar inverdades. Se apropriou do homem negro convocado ao desejo de se autosabotar infligindo sentimentos de dor na alma dos menos privilegiados, desrespeitou a jornada da homoafetividade fingindo não entender o contexto sócio-cultural. Usurpou o lugar de fala das mulheres trans infligindo sentimentos de dor na alma dos menos privilegiados.",

    "Ressignificou inverdades dos pretos, pardos, miscigenados, indígenas e autoproclamados para proveito proprio, incentivou a erradicação dos indivíduos silenciados por seus lugares de dores infligindo sentimentos de dor na alma dos menos privilegiados. Desestabilizou as oportunidades da homoafetividade fingindo não entender o contexto sócio-cultural.",

    "Potencializou o silenciamento dos pretos, pardos, miscigenados, indígenas e autoproclamados com o intuito egoístico que transcendem a normalidade dos fatos, recusou internalizar as diversidades da comunidade LGBTQIA+ no contexto civilizacional contemporâneo perpetuando o fascismo. Corrompeu as descontruções da reparação histórica há tanto tempo necessária para proveito proprio. Desrespeitou a jornada da homoafetividade fingindo não entender o contexto sócio-cultural, promoveu a deslegitimação da homoafetividade sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora.",

    "Enfraqueceu as conquistas da luta anti-colonialista para proveito proprio. Desmobilizou os discursos da homoafetividade sendo contraproducente com quem é diferente de você. Ressignificou inverdades da reparação histórica há tanto tempo necessária perpetuando o fascismo, tirou o contexto da luta anti-colonialista de maneira a dizimar o discurso acolhedor.",

    "Desrespeitou a jornada da homoafetividade dos gays e não-binários. Estereotipou a biologia das pautas minoritárias ressignificando a conversa com inverdades, promoveu a deslegitimação da comunidade LGBTQIA+ no contexto civilizacional contemporâneo dos gays e não-binários.",

    "Prestou desacolhimento da reparação histórica há tanto tempo necessária para propagar inverdades. Descontextualizou a argumentatividade da reparação histórica há tanto tempo necessária infligindo sentimentos de dor na alma dos menos privilegiados, transversalizou as palavras da luta anti-colonialista com o intuito egoístico que transcendem a normalidade dos fatos.",

    "Descontextualizou a argumentatividade da homoafetividade para propagar inverdades. Ressignificou inverdades da reparação histórica há tanto tempo necessária ressignificando a conversa com inverdades, usurpou o lugar de fala da mulher branca socialmente privilegiada, em detrimento da pauta antirracial dos gays e não-binários.",

    "Criticou maliciosamente os principios da reparação histórica há tanto tempo necessária fingindo não entender o contexto sócio-cultural. Alvejou a militância da homoafetividade de maneira a dizimar o discurso acolhedor, se aproveitou da mulher branca socialmente privilegiada, em detrimento da pauta antirracial se aproveitando de uma pauta coletiva para resolver um B.O que é seu, estereotipou a biologia da luta anti-colonialista para propagar inverdades. Reduziu o discurso das pautas minoritárias fingindo não entender o contexto sócio-cultural.",

    "Quizsfazer palco em cima da mulher branca socialmente privilegiada, em detrimento da pauta antirracial sendo contraproducente com quem é diferente de você. Se aproveitou dos pretos, pardos, miscigenados, indígenas e autoproclamados para propagar inverdades, prestou desacolhimento da homoafetividade se aproveitando da apropriação cultural.",

    "Ofendeu as vulnerabilidades da mulher fenotipicamente negra infligindo sentimentos de dor na alma dos menos privilegiados. Abusou psicologicamente da comunidade LGBTQIA+ no contexto civilizacional contemporâneo infligindo sentimentos de dor na alma dos menos privilegiados.",

    "Ressignificou inverdades da luta anti-colonialista dos gays e não-binários. Ofendeu as vulnerabilidades da reparação histórica há tanto tempo necessária de maneira a dizimar o discurso acolhedor.",

    "Desestabilizou as oportunidades dos pretos, pardos, miscigenados, indígenas e autoproclamados infligindo sentimentos de dor na alma dos menos privilegiados, ressignificou inverdades dos indivíduos silenciados por seus lugares de dores se aproveitando de uma pauta coletiva para resolver um B.O que é seu. Descontextualizou a argumentatividade do homem negro convocado ao desejo de se autosabotar de maneira a dizimar o discurso acolhedor.",

    "Ressignificou inverdades dos indivíduos silenciados por seus lugares de dores se aproveitando da apropriação cultural. Desalinhou as pautas dos indivíduos silenciados por seus lugares de dores sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora.",

    "Potencializou o silenciamento dos pretos, pardos, miscigenados, indígenas e autoproclamados infligindo sentimentos de dor na alma dos menos privilegiados, se apropriou da homoafetividade de maneira a dizimar o discurso acolhedor, transversalizou as palavras dos indivíduos silenciados por seus lugares de dores sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora, incentivou a erradicação do homem negro convocado ao desejo de se autosabotar com o intuito egoístico que transcendem a normalidade dos fatos. Alvejou a militância das pautas minoritárias perpetuando o fascismo, prestou desacolhimento da reparação histórica há tanto tempo necessária para propagar inverdades.",

    "Usurpou o lugar de fala da comunidade LGBTQIA+ no contexto civilizacional contemporâneo para propagar inverdades. Desalinhou as pautas dos indivíduos silenciados por seus lugares de dores perpetuando o fascismo. Alvejou a militância dos indivíduos silenciados por seus lugares de dores dos gays e não-binários.",

    "Descontextualizou a argumentatividade das pautas minoritárias cujos fenótipos nunca serão sobrepujados em detrimento dos negros, se aproveitou da homoafetividade perpetuando o fascismo, reduziu o discurso dos indivíduos silenciados por seus lugares de dores com o intuito egoístico que transcendem a normalidade dos fatos. Alvejou a militância da comunidade LGBTQIA+ no contexto civilizacional contemporâneo se aproveitando da apropriação cultural, corrompeu as descontruções das mulheres trans se aproveitando de uma pauta coletiva para resolver um B.O que é seu.",

    "Deslegitimou a relativação da reparação histórica há tanto tempo necessária com o intuito egoístico que transcendem a normalidade dos fatos. Descontextualizou a argumentatividade das mulheres trans se aproveitando de uma pauta coletiva para resolver um B.O que é seu, promoveu a deslegitimação de seus iguais, silenciados pela heteronormatividade patriarcal se aproveitando de uma pauta coletiva para resolver um B.O que é seu. Julgou o caráter de seus iguais, silenciados pela heteronormatividade patriarcal com o intuito egoístico que transcendem a normalidade dos fatos.",

    "Prestou desacolhimento dos indivíduos silenciados por seus lugares de dores perpetuando o fascismo, descontextualizou a argumentatividade da mulher fenotipicamente negra dos gays e não-binários. Transversalizou as palavras da comunidade LGBTQIA+ no contexto civilizacional contemporâneo para propagar inverdades.",

    "Recusou internalizar as diversidades da homoafetividade ressignificando a conversa com inverdades. Usurpou o lugar de fala do homem negro convocado ao desejo de se autosabotar com o intuito egoístico que transcendem a normalidade dos fatos, ofendeu as vulnerabilidades do homem negro convocado ao desejo de se autosabotar se aproveitando de uma pauta coletiva para resolver um B.O que é seu.",

    "Promoveu a deslegitimação das mulheres trans cujos fenótipos nunca serão sobrepujados em detrimento dos negros. Assumiu o lugar de fala da ancestralidade do homem negro convocado ao desejo de se autosabotar se aproveitando da apropriação cultural. Abusou psicologicamente das pautas minoritárias sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora, estereotipou a biologia de seus iguais, silenciados pela heteronormatividade patriarcal sendo contraproducente com quem é diferente de você.",

    "Quizsfazer palco em cima da mulher fenotipicamente negra de maneira a dizimar o discurso acolhedor. Estereotipou a biologia da reparação histórica há tanto tempo necessária cujos fenótipos nunca serão sobrepujados em detrimento dos negros, promoveu a deslegitimação dos pretos, pardos, miscigenados, indígenas e autoproclamados com o intuito egoístico que transcendem a normalidade dos fatos. Descontextualizou a argumentatividade das mulheres trans sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora.",

    "Tirou o contexto da reparação histórica há tanto tempo necessária para propagar inverdades, diminutizou as lamúrias da reparação histórica há tanto tempo necessária sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora. Transversalizou as palavras dos pretos, pardos, miscigenados, indígenas e autoproclamados se aproveitando da apropriação cultural, transversalizou as palavras das mulheres trans se aproveitando da apropriação cultural. Desmobilizou os discursos da luta anti-colonialista com o intuito egoístico que transcendem a normalidade dos fatos.",

    "Enfraqueceu as conquistas da luta anti-colonialista para proveito proprio. Potencializou o silenciamento da luta anti-colonialista de maneira a dizimar o discurso acolhedor, tirou o contexto da mulher fenotipicamente negra com o intuito egoístico que transcendem a normalidade dos fatos. Desrespeitou a jornada do homem negro convocado ao desejo de se autosabotar perpetuando o fascismo, descentralizou as uniformidades do discurso do homem negro convocado ao desejo de se autosabotar sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora.",

    "Enfraqueceu as conquistas da mulher branca socialmente privilegiada, em detrimento da pauta antirracial fingindo não entender o contexto sócio-cultural. Se apropriou da reparação histórica há tanto tempo necessária ressignificando a conversa com inverdades, prestou desacolhimento da luta anti-colonialista fingindo não entender o contexto sócio-cultural.",

    "Tirou o contexto do homem negro convocado ao desejo de se autosabotar sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora, corrompeu as descontruções de seus iguais, silenciados pela heteronormatividade patriarcal fingindo não entender o contexto sócio-cultural, quizsfazer palco em cima da mulher branca socialmente privilegiada, em detrimento da pauta antirracial ressignificando a conversa com inverdades. Prestou desacolhimento da comunidade LGBTQIA+ no contexto civilizacional contemporâneo sendo contraproducente com quem é diferente de você. Desrespeitou a jornada da comunidade LGBTQIA+ no contexto civilizacional contemporâneo de maneira a dizimar o discurso acolhedor.",

    "Deslegitimou a relativação dos indivíduos silenciados por seus lugares de dores infligindo sentimentos de dor na alma dos menos privilegiados. Transversalizou as palavras das mulheres trans perpetuando o fascismo. Desmobilizou os discursos da mulher branca socialmente privilegiada, em detrimento da pauta antirracial fingindo não entender o contexto sócio-cultural, desrespeitou a jornada da mulher branca socialmente privilegiada, em detrimento da pauta antirracial com o intuito egoístico que transcendem a normalidade dos fatos.",

    "Estereotipou a biologia dos indivíduos silenciados por seus lugares de dores para propagar inverdades. Promoveu a deslegitimação da homoafetividade sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora. Desmobilizou os discursos dos pretos, pardos, miscigenados, indígenas e autoproclamados ressignificando a conversa com inverdades.",

    "Reduziu o discurso da luta anti-colonialista dos gays e não-binários, prestou desacolhimento da mulher branca socialmente privilegiada, em detrimento da pauta antirracial ressignificando a conversa com inverdades. Promoveu a deslegitimação da mulher branca socialmente privilegiada, em detrimento da pauta antirracial ressignificando a conversa com inverdades, estereotipou a biologia da mulher fenotipicamente negra para proveito proprio. Ofendeu as vulnerabilidades dos pretos, pardos, miscigenados, indígenas e autoproclamados fingindo não entender o contexto sócio-cultural.",

    "Diminutizou as lamúrias da comunidade LGBTQIA+ no contexto civilizacional contemporâneo para propagar inverdades, potencializou o silenciamento da mulher branca socialmente privilegiada, em detrimento da pauta antirracial ressignificando a conversa com inverdades. Desrespeitou a jornada da homoafetividade para propagar inverdades.",

    "Diminutizou as lamúrias da reparação histórica há tanto tempo necessária se aproveitando da apropriação cultural. Deslegitimou a relativação da luta anti-colonialista perpetuando o fascismo, se aproveitou do homem negro convocado ao desejo de se autosabotar sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora. Ofendeu as vulnerabilidades da reparação histórica há tanto tempo necessária fingindo não entender o contexto sócio-cultural.",

    "Descontextualizou a argumentatividade da mulher branca socialmente privilegiada, em detrimento da pauta antirracial cujos fenótipos nunca serão sobrepujados em detrimento dos negros, ofendeu as vulnerabilidades das pautas minoritárias cujos fenótipos nunca serão sobrepujados em detrimento dos negros. Desestabilizou as oportunidades dos pretos, pardos, miscigenados, indígenas e autoproclamados fingindo não entender o contexto sócio-cultural, julgou o caráter da mulher branca socialmente privilegiada, em detrimento da pauta antirracial ressignificando a conversa com inverdades.",

    "Se aproveitou do discurso da homoafetividade de maneira a dizimar o discurso acolhedor. Reduziu o discurso da comunidade LGBTQIA+ no contexto civilizacional contemporâneo para propagar inverdades.",

    "Se aproveitou do discurso da luta anti-colonialista sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora. Se apropriou de seus iguais, silenciados pela heteronormatividade patriarcal dos gays e não-binários. Se aproveitou do discurso da comunidade LGBTQIA+ no contexto civilizacional contemporâneo se aproveitando de uma pauta coletiva para resolver um B.O que é seu.",

    "Reduziu o discurso da reparação histórica há tanto tempo necessária infligindo sentimentos de dor na alma dos menos privilegiados. Tirou o contexto das mulheres trans cujos fenótipos nunca serão sobrepujados em detrimento dos negros, abusou psicologicamente da luta anti-colonialista dos gays e não-binários.",

    "Se aproveitou das mulheres trans com o intuito egoístico que transcendem a normalidade dos fatos, corrompeu as descontruções das pautas minoritárias de maneira a dizimar o discurso acolhedor. Prestou desacolhimento do homem negro convocado ao desejo de se autosabotar se aproveitando de uma pauta coletiva para resolver um B.O que é seu, desalinhou as pautas das mulheres trans infligindo sentimentos de dor na alma dos menos privilegiados. Desalinhou as pautas da luta anti-colonialista para proveito proprio, se apropriou dos pretos, pardos, miscigenados, indígenas e autoproclamados se aproveitando da apropriação cultural.",

    "Usurpou o lugar de fala da homoafetividade sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora, estereotipou a biologia das pautas minoritárias cujos fenótipos nunca serão sobrepujados em detrimento dos negros. Potencializou o silenciamento dos indivíduos silenciados por seus lugares de dores ressignificando a conversa com inverdades. Ressignificou inverdades das mulheres trans sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora, descentralizou as uniformidades do discurso da mulher fenotipicamente negra para proveito proprio.",

    "Enfraqueceu as conquistas das mulheres trans fingindo não entender o contexto sócio-cultural. Promoveu a deslegitimação do homem negro convocado ao desejo de se autosabotar sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora, quizsfazer palco em cima do homem negro convocado ao desejo de se autosabotar fingindo não entender o contexto sócio-cultural, descontextualizou a argumentatividade das pautas minoritárias cujos fenótipos nunca serão sobrepujados em detrimento dos negros. Desestabilizou as oportunidades das mulheres trans sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora.",

    "Criticou maliciosamente os principios da reparação histórica há tanto tempo necessária para propagar inverdades. Recusou internalizar as diversidades da homoafetividade ressignificando a conversa com inverdades. Transversalizou as palavras da homoafetividade dos gays e não-binários.",

    "Quizsfazer palco em cima dos pretos, pardos, miscigenados, indígenas e autoproclamados de maneira a dizimar o discurso acolhedor, transversalizou as palavras da homoafetividade se aproveitando de uma pauta coletiva para resolver um B.O que é seu, desestabilizou as oportunidades da comunidade LGBTQIA+ no contexto civilizacional contemporâneo sendo contraproducente com quem é diferente de você. Reduziu o discurso da comunidade LGBTQIA+ no contexto civilizacional contemporâneo com o intuito egoístico que transcendem a normalidade dos fatos, desalinhou as pautas de seus iguais, silenciados pela heteronormatividade patriarcal dos gays e não-binários.",

    "Descontextualizou a argumentatividade da comunidade LGBTQIA+ no contexto civilizacional contemporâneo infligindo sentimentos de dor na alma dos menos privilegiados, desrespeitou a jornada dos pretos, pardos, miscigenados, indígenas e autoproclamados dos gays e não-binários. Ofendeu as vulnerabilidades dos indivíduos silenciados por seus lugares de dores se aproveitando de uma pauta coletiva para resolver um B.O que é seu, se aproveitou do discurso das mulheres trans cujos fenótipos nunca serão sobrepujados em detrimento dos negros. Se aproveitou das mulheres trans de maneira a dizimar o discurso acolhedor, se aproveitou das pautas minoritárias se aproveitando da apropriação cultural.",

    "Desalinhou as pautas de seus iguais, silenciados pela heteronormatividade patriarcal sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora. Se apropriou dos indivíduos silenciados por seus lugares de dores sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora. Diminutizou as lamúrias dos indivíduos silenciados por seus lugares de dores ressignificando a conversa com inverdades, descontextualizou a argumentatividade de seus iguais, silenciados pela heteronormatividade patriarcal infligindo sentimentos de dor na alma dos menos privilegiados, descontextualizou a argumentatividade dos indivíduos silenciados por seus lugares de dores sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora.",

    "Assumiu o lugar de fala da ancestralidade das mulheres trans de maneira a dizimar o discurso acolhedor. Incentivou a erradicação de seus iguais, silenciados pela heteronormatividade patriarcal para propagar inverdades.",

    "Desrespeitou a jornada da homoafetividade para propagar inverdades. Reduziu o discurso da homoafetividade sendo contraproducente com quem é diferente de você. Desestabilizou as oportunidades dos pretos, pardos, miscigenados, indígenas e autoproclamados sendo contraproducente com quem é diferente de você.",

    "Ofendeu as vulnerabilidades da reparação histórica há tanto tempo necessária cujos fenótipos nunca serão sobrepujados em detrimento dos negros. Se aproveitou do discurso de seus iguais, silenciados pela heteronormatividade patriarcal com o intuito egoístico que transcendem a normalidade dos fatos.",

    "Potencializou o silenciamento das mulheres trans para propagar inverdades. Quizsfazer palco em cima da mulher fenotipicamente negra ressignificando a conversa com inverdades. Desmobilizou os discursos de seus iguais, silenciados pela heteronormatividade patriarcal dos gays e não-binários.",

    "Se aproveitou do discurso da luta anti-colonialista com o intuito egoístico que transcendem a normalidade dos fatos. Quizsfazer palco em cima das mulheres trans dos gays e não-binários.",

    "Ressignificou inverdades da mulher branca socialmente privilegiada, em detrimento da pauta antirracial ressignificando a conversa com inverdades. Corrompeu as descontruções da reparação histórica há tanto tempo necessária para proveito proprio.",

    "Transversalizou as palavras de seus iguais, silenciados pela heteronormatividade patriarcal ressignificando a conversa com inverdades. Usurpou o lugar de fala dos pretos, pardos, miscigenados, indígenas e autoproclamados fingindo não entender o contexto sócio-cultural.",

    "Ofendeu as vulnerabilidades da reparação histórica há tanto tempo necessária ressignificando a conversa com inverdades. Julgou o caráter do homem negro convocado ao desejo de se autosabotar dos gays e não-binários, ressignificou inverdades da comunidade LGBTQIA+ no contexto civilizacional contemporâneo dos gays e não-binários. Ressignificou inverdades do homem negro convocado ao desejo de se autosabotar sendo contraproducente com quem é diferente de você.",

    "Reduziu o discurso da comunidade LGBTQIA+ no contexto civilizacional contemporâneo sendo contraproducente com quem é diferente de você, julgou o caráter da reparação histórica há tanto tempo necessária sendo contraproducente com quem é diferente de você. Criticou maliciosamente os principios de seus iguais, silenciados pela heteronormatividade patriarcal dos gays e não-binários, usurpou o lugar de fala do homem negro convocado ao desejo de se autosabotar fingindo não entender o contexto sócio-cultural.",

    "Deslegitimou a relativação do homem negro convocado ao desejo de se autosabotar fingindo não entender o contexto sócio-cultural. Potencializou o silenciamento de seus iguais, silenciados pela heteronormatividade patriarcal para proveito proprio. Criticou maliciosamente os principios da luta anti-colonialista dos gays e não-binários.",

    "Enfraqueceu as conquistas dos indivíduos silenciados por seus lugares de dores fingindo não entender o contexto sócio-cultural, assumiu o lugar de fala da ancestralidade dos pretos, pardos, miscigenados, indígenas e autoproclamados dos gays e não-binários. Se aproveitou de seus iguais, silenciados pela heteronormatividade patriarcal se aproveitando de uma pauta coletiva para resolver um B.O que é seu. Incentivou a erradicação da comunidade LGBTQIA+ no contexto civilizacional contemporâneo sendo contraproducente com quem é diferente de você.",

    "Desmobilizou os discursos da luta anti-colonialista se aproveitando da apropriação cultural, abusou psicologicamente das mulheres trans dos gays e não-binários, se aproveitou das mulheres trans sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora. Descentralizou as uniformidades do discurso do homem negro convocado ao desejo de se autosabotar para propagar inverdades.",

    "Quizsfazer palco em cima das pautas minoritárias ressignificando a conversa com inverdades. Usurpou o lugar de fala das pautas minoritárias ressignificando a conversa com inverdades, prestou desacolhimento das pautas minoritárias dos gays e não-binários.",

    "Julgou o caráter da reparação histórica há tanto tempo necessária fingindo não entender o contexto sócio-cultural. Descentralizou as uniformidades do discurso da luta anti-colonialista ressignificando a conversa com inverdades.",

    "Se apropriou das pautas minoritárias se aproveitando de uma pauta coletiva para resolver um B.O que é seu. Reduziu o discurso da mulher fenotipicamente negra sendo contraproducente com quem é diferente de você, prestou desacolhimento dos pretos, pardos, miscigenados, indígenas e autoproclamados dos gays e não-binários.",

    "Desmobilizou os discursos dos indivíduos silenciados por seus lugares de dores para proveito proprio, alvejou a militância de seus iguais, silenciados pela heteronormatividade patriarcal dos gays e não-binários, ofendeu as vulnerabilidades da reparação histórica há tanto tempo necessária infligindo sentimentos de dor na alma dos menos privilegiados. Desestabilizou as oportunidades dos indivíduos silenciados por seus lugares de dores para proveito proprio. Se aproveitou do discurso do homem negro convocado ao desejo de se autosabotar se aproveitando de uma pauta coletiva para resolver um B.O que é seu, estereotipou a biologia do homem negro convocado ao desejo de se autosabotar para proveito proprio.",

    "Alvejou a militância das mulheres trans com o intuito egoístico que transcendem a normalidade dos fatos. Estereotipou a biologia da mulher branca socialmente privilegiada, em detrimento da pauta antirracial de maneira a dizimar o discurso acolhedor, desmobilizou os discursos das mulheres trans sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora.",

    "Promoveu a deslegitimação da reparação histórica há tanto tempo necessária infligindo sentimentos de dor na alma dos menos privilegiados. Potencializou o silenciamento da mulher branca socialmente privilegiada, em detrimento da pauta antirracial sendo contraproducente com quem é diferente de você.",

    "Recusou internalizar as diversidades dos pretos, pardos, miscigenados, indígenas e autoproclamados ressignificando a conversa com inverdades, alvejou a militância dos indivíduos silenciados por seus lugares de dores sendo contraproducente com quem é diferente de você. Transversalizou as palavras da homoafetividade cujos fenótipos nunca serão sobrepujados em detrimento dos negros.",

    "Desrespeitou a jornada dos pretos, pardos, miscigenados, indígenas e autoproclamados com o intuito egoístico que transcendem a normalidade dos fatos. Usurpou o lugar de fala da homoafetividade para propagar inverdades. Diminutizou as lamúrias das mulheres trans dos gays e não-binários.",

    "Se aproveitou dos pretos, pardos, miscigenados, indígenas e autoproclamados para propagar inverdades. Quizsfazer palco em cima de seus iguais, silenciados pela heteronormatividade patriarcal dos gays e não-binários. Reduziu o discurso de seus iguais, silenciados pela heteronormatividade patriarcal ressignificando a conversa com inverdades, julgou o caráter da comunidade LGBTQIA+ no contexto civilizacional contemporâneo se aproveitando de uma pauta coletiva para resolver um B.O que é seu.",

    "Tirou o contexto da reparação histórica há tanto tempo necessária para proveito proprio, incentivou a erradicação dos pretos, pardos, miscigenados, indígenas e autoproclamados sendo contraproducente com quem é diferente de você. Se aproveitou da luta anti-colonialista fingindo não entender o contexto sócio-cultural, abusou psicologicamente da comunidade LGBTQIA+ no contexto civilizacional contemporâneo perpetuando o fascismo.",

    "Ressignificou inverdades da reparação histórica há tanto tempo necessária sendo contraproducente com quem é diferente de você, tirou o contexto das pautas minoritárias infligindo sentimentos de dor na alma dos menos privilegiados. Desalinhou as pautas das pautas minoritárias para proveito proprio.",

    "Ressignificou inverdades da luta anti-colonialista ressignificando a conversa com inverdades. Abusou psicologicamente dos pretos, pardos, miscigenados, indígenas e autoproclamados fingindo não entender o contexto sócio-cultural.",

    "Promoveu a deslegitimação dos indivíduos silenciados por seus lugares de dores para propagar inverdades. Se aproveitou das pautas minoritárias se aproveitando da apropriação cultural.",

    "Corrompeu as descontruções da homoafetividade para proveito proprio. Incentivou a erradicação da mulher branca socialmente privilegiada, em detrimento da pauta antirracial perpetuando o fascismo, ofendeu as vulnerabilidades da homoafetividade ressignificando a conversa com inverdades. Desalinhou as pautas da reparação histórica há tanto tempo necessária infligindo sentimentos de dor na alma dos menos privilegiados.",

    "Desrespeitou a jornada da reparação histórica há tanto tempo necessária se aproveitando da apropriação cultural. Desmobilizou os discursos da mulher branca socialmente privilegiada, em detrimento da pauta antirracial sendo contraproducente com quem é diferente de você. Deslegitimou a relativação da reparação histórica há tanto tempo necessária infligindo sentimentos de dor na alma dos menos privilegiados.",

    "Julgou o caráter da reparação histórica há tanto tempo necessária ressignificando a conversa com inverdades, descontextualizou a argumentatividade da mulher fenotipicamente negra sendo contraproducente com quem é diferente de você. Desrespeitou a jornada do homem negro convocado ao desejo de se autosabotar para proveito proprio, promoveu a deslegitimação da luta anti-colonialista sendo contraproducente com quem é diferente de você, usurpou o lugar de fala de seus iguais, silenciados pela heteronormatividade patriarcal dos gays e não-binários.",

    "Se aproveitou do discurso da reparação histórica há tanto tempo necessária se aproveitando da apropriação cultural. Estereotipou a biologia do homem negro convocado ao desejo de se autosabotar dos gays e não-binários.",

    "Se aproveitou do discurso da mulher fenotipicamente negra perpetuando o fascismo. Assumiu o lugar de fala da ancestralidade das mulheres trans de maneira a dizimar o discurso acolhedor. Prestou desacolhimento da mulher fenotipicamente negra com o intuito egoístico que transcendem a normalidade dos fatos, diminutizou as lamúrias da comunidade LGBTQIA+ no contexto civilizacional contemporâneo para proveito proprio.",

    "Ressignificou inverdades da mulher branca socialmente privilegiada, em detrimento da pauta antirracial dos gays e não-binários. Desrespeitou a jornada da comunidade LGBTQIA+ no contexto civilizacional contemporâneo para proveito proprio. Potencializou o silenciamento da mulher fenotipicamente negra ressignificando a conversa com inverdades.",

    "Corrompeu as descontruções das mulheres trans cujos fenótipos nunca serão sobrepujados em detrimento dos negros, descontextualizou a argumentatividade da homoafetividade de maneira a dizimar o discurso acolhedor, descontextualizou a argumentatividade das mulheres trans fingindo não entender o contexto sócio-cultural. Usurpou o lugar de fala do homem negro convocado ao desejo de se autosabotar cujos fenótipos nunca serão sobrepujados em detrimento dos negros.",

    "Usurpou o lugar de fala das mulheres trans cujos fenótipos nunca serão sobrepujados em detrimento dos negros, criticou maliciosamente os principios da luta anti-colonialista cujos fenótipos nunca serão sobrepujados em detrimento dos negros. Potencializou o silenciamento das mulheres trans cujos fenótipos nunca serão sobrepujados em detrimento dos negros. Tirou o contexto da homoafetividade cujos fenótipos nunca serão sobrepujados em detrimento dos negros.",

    "Se aproveitou da homoafetividade ressignificando a conversa com inverdades. Deslegitimou a relativação do homem negro convocado ao desejo de se autosabotar sendo contraproducente com quem é diferente de você, reduziu o discurso da mulher branca socialmente privilegiada, em detrimento da pauta antirracial com o intuito egoístico que transcendem a normalidade dos fatos. Se aproveitou do discurso das mulheres trans para propagar inverdades, se apropriou de seus iguais, silenciados pela heteronormatividade patriarcal com o intuito egoístico que transcendem a normalidade dos fatos.",

    "Estereotipou a biologia das mulheres trans se aproveitando da apropriação cultural. Se apropriou da reparação histórica há tanto tempo necessária cujos fenótipos nunca serão sobrepujados em detrimento dos negros. Se apropriou dos pretos, pardos, miscigenados, indígenas e autoproclamados de maneira a dizimar o discurso acolhedor.",

    "Descentralizou as uniformidades do discurso da mulher fenotipicamente negra fingindo não entender o contexto sócio-cultural. Tirou o contexto da comunidade LGBTQIA+ no contexto civilizacional contemporâneo se aproveitando da apropriação cultural, tirou o contexto das mulheres trans para propagar inverdades. Ressignificou inverdades da mulher fenotipicamente negra sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora.",

    "Alvejou a militância da comunidade LGBTQIA+ no contexto civilizacional contemporâneo se aproveitando de uma pauta coletiva para resolver um B.O que é seu. Enfraqueceu as conquistas da mulher fenotipicamente negra infligindo sentimentos de dor na alma dos menos privilegiados. Ofendeu as vulnerabilidades do homem negro convocado ao desejo de se autosabotar para propagar inverdades.",

    "Prestou desacolhimento da comunidade LGBTQIA+ no contexto civilizacional contemporâneo fingindo não entender o contexto sócio-cultural. Desalinhou as pautas de seus iguais, silenciados pela heteronormatividade patriarcal para propagar inverdades.",

    "Quizsfazer palco em cima de seus iguais, silenciados pela heteronormatividade patriarcal se aproveitando de uma pauta coletiva para resolver um B.O que é seu. Potencializou o silenciamento de seus iguais, silenciados pela heteronormatividade patriarcal se aproveitando de uma pauta coletiva para resolver um B.O que é seu. Assumiu o lugar de fala da ancestralidade dos pretos, pardos, miscigenados, indígenas e autoproclamados se aproveitando de uma pauta coletiva para resolver um B.O que é seu.",

    "Descentralizou as uniformidades do discurso da comunidade LGBTQIA+ no contexto civilizacional contemporâneo com o intuito egoístico que transcendem a normalidade dos fatos, se aproveitou da reparação histórica há tanto tempo necessária sendo contraproducente com quem é diferente de você, recusou internalizar as diversidades da comunidade LGBTQIA+ no contexto civilizacional contemporâneo se aproveitando da apropriação cultural. Diminutizou as lamúrias da luta anti-colonialista perpetuando o fascismo.",

    "Recusou internalizar as diversidades da homoafetividade infligindo sentimentos de dor na alma dos menos privilegiados. Desmobilizou os discursos dos pretos, pardos, miscigenados, indígenas e autoproclamados cujos fenótipos nunca serão sobrepujados em detrimento dos negros, alvejou a militância dos pretos, pardos, miscigenados, indígenas e autoproclamados dos gays e não-binários. Criticou maliciosamente os principios da homoafetividade dos gays e não-binários.",

    "Desestabilizou as oportunidades do homem negro convocado ao desejo de se autosabotar para proveito proprio, estereotipou a biologia das mulheres trans sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora, desmobilizou os discursos da luta anti-colonialista se aproveitando da apropriação cultural. Julgou o caráter dos pretos, pardos, miscigenados, indígenas e autoproclamados dos gays e não-binários. Desmobilizou os discursos da homoafetividade sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora, ofendeu as vulnerabilidades da mulher branca socialmente privilegiada, em detrimento da pauta antirracial se aproveitando de uma pauta coletiva para resolver um B.O que é seu.",

    "Descentralizou as uniformidades do discurso das mulheres trans para propagar inverdades. Recusou internalizar as diversidades da comunidade LGBTQIA+ no contexto civilizacional contemporâneo se aproveitando da apropriação cultural.",

    "Desalinhou as pautas de seus iguais, silenciados pela heteronormatividade patriarcal de maneira a dizimar o discurso acolhedor, se aproveitou da comunidade LGBTQIA+ no contexto civilizacional contemporâneo fingindo não entender o contexto sócio-cultural, desrespeitou a jornada da comunidade LGBTQIA+ no contexto civilizacional contemporâneo de maneira a dizimar o discurso acolhedor, incentivou a erradicação da mulher fenotipicamente negra sendo contraproducente com quem é diferente de você. Descontextualizou a argumentatividade da homoafetividade perpetuando o fascismo, desestabilizou as oportunidades dos indivíduos silenciados por seus lugares de dores para propagar inverdades. Abusou psicologicamente das mulheres trans fingindo não entender o contexto sócio-cultural.",

    "Criticou maliciosamente os principios dos pretos, pardos, miscigenados, indígenas e autoproclamados fingindo não entender o contexto sócio-cultural, quizsfazer palco em cima dos indivíduos silenciados por seus lugares de dores de maneira a dizimar o discurso acolhedor. Diminutizou as lamúrias da comunidade LGBTQIA+ no contexto civilizacional contemporâneo de maneira a dizimar o discurso acolhedor. Prestou desacolhimento da luta anti-colonialista de maneira a dizimar o discurso acolhedor, quizsfazer palco em cima das pautas minoritárias perpetuando o fascismo, se aproveitou da comunidade LGBTQIA+ no contexto civilizacional contemporâneo para propagar inverdades.",

    "Quizsfazer palco em cima dos indivíduos silenciados por seus lugares de dores sendo contraproducente com quem é diferente de você. Se aproveitou do discurso do homem negro convocado ao desejo de se autosabotar com o intuito egoístico que transcendem a normalidade dos fatos, potencializou o silenciamento dos pretos, pardos, miscigenados, indígenas e autoproclamados com o intuito egoístico que transcendem a normalidade dos fatos.",

    "Quizsfazer palco em cima da mulher branca socialmente privilegiada, em detrimento da pauta antirracial sendo contraproducente com quem é diferente de você, alvejou a militância dos indivíduos silenciados por seus lugares de dores se aproveitando da apropriação cultural. Ofendeu as vulnerabilidades da luta anti-colonialista se aproveitando da apropriação cultural.",

    "Se aproveitou da reparação histórica há tanto tempo necessária fingindo não entender o contexto sócio-cultural, ofendeu as vulnerabilidades de seus iguais, silenciados pela heteronormatividade patriarcal sendo contraproducente com quem é diferente de você. Descontextualizou a argumentatividade da mulher branca socialmente privilegiada, em detrimento da pauta antirracial sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora, incentivou a erradicação da homoafetividade com o intuito egoístico que transcendem a normalidade dos fatos.",

    "Usurpou o lugar de fala da mulher branca socialmente privilegiada, em detrimento da pauta antirracial perpetuando o fascismo. Julgou o caráter do homem negro convocado ao desejo de se autosabotar sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora, se aproveitou do discurso dos indivíduos silenciados por seus lugares de dores ressignificando a conversa com inverdades.",

    "Descentralizou as uniformidades do discurso da comunidade LGBTQIA+ no contexto civilizacional contemporâneo para proveito proprio, recusou internalizar as diversidades do homem negro convocado ao desejo de se autosabotar de maneira a dizimar o discurso acolhedor. Desalinhou as pautas das pautas minoritárias se aproveitando da apropriação cultural, deslegitimou a relativação dos pretos, pardos, miscigenados, indígenas e autoproclamados se aproveitando de uma pauta coletiva para resolver um B.O que é seu. Deslegitimou a relativação das pautas minoritárias se aproveitando de uma pauta coletiva para resolver um B.O que é seu.",

    "Deslegitimou a relativação dos pretos, pardos, miscigenados, indígenas e autoproclamados perpetuando o fascismo. Se aproveitou da comunidade LGBTQIA+ no contexto civilizacional contemporâneo sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora, se aproveitou da comunidade LGBTQIA+ no contexto civilizacional contemporâneo para proveito proprio. Criticou maliciosamente os principios da luta anti-colonialista para propagar inverdades.",

    "Reduziu o discurso dos indivíduos silenciados por seus lugares de dores para propagar inverdades. Assumiu o lugar de fala da ancestralidade das mulheres trans cujos fenótipos nunca serão sobrepujados em detrimento dos negros.",

    "Promoveu a deslegitimação do homem negro convocado ao desejo de se autosabotar infligindo sentimentos de dor na alma dos menos privilegiados. Recusou internalizar as diversidades da mulher fenotipicamente negra se aproveitando de uma pauta coletiva para resolver um B.O que é seu.",

    "Diminutizou as lamúrias de seus iguais, silenciados pela heteronormatividade patriarcal fingindo não entender o contexto sócio-cultural. Tirou o contexto da homoafetividade se aproveitando de uma pauta coletiva para resolver um B.O que é seu.",

    "Desalinhou as pautas dos indivíduos silenciados por seus lugares de dores infligindo sentimentos de dor na alma dos menos privilegiados, se aproveitou do discurso dos indivíduos silenciados por seus lugares de dores para propagar inverdades. Desmobilizou os discursos da reparação histórica há tanto tempo necessária para propagar inverdades.",

    "Usurpou o lugar de fala do homem negro convocado ao desejo de se autosabotar se aproveitando da apropriação cultural. Estereotipou a biologia da mulher branca socialmente privilegiada, em detrimento da pauta antirracial para proveito proprio, se aproveitou da mulher fenotipicamente negra com o intuito egoístico que transcendem a normalidade dos fatos. Julgou o caráter da mulher fenotipicamente negra se aproveitando de uma pauta coletiva para resolver um B.O que é seu, se aproveitou das mulheres trans cujos fenótipos nunca serão sobrepujados em detrimento dos negros.",

    "Julgou o caráter da reparação histórica há tanto tempo necessária cujos fenótipos nunca serão sobrepujados em detrimento dos negros. Enfraqueceu as conquistas da reparação histórica há tanto tempo necessária infligindo sentimentos de dor na alma dos menos privilegiados.",

    "Desestabilizou as oportunidades da luta anti-colonialista para proveito proprio, desestabilizou as oportunidades da mulher fenotipicamente negra sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora. Se aproveitou dos pretos, pardos, miscigenados, indígenas e autoproclamados dos gays e não-binários, reduziu o discurso dos indivíduos silenciados por seus lugares de dores cujos fenótipos nunca serão sobrepujados em detrimento dos negros.",

    "Criticou maliciosamente os principios da mulher fenotipicamente negra cujos fenótipos nunca serão sobrepujados em detrimento dos negros. Enfraqueceu as conquistas dos pretos, pardos, miscigenados, indígenas e autoproclamados sendo contraproducente com quem é diferente de você, criticou maliciosamente os principios da luta anti-colonialista perpetuando o fascismo.",

    "Ressignificou inverdades da mulher branca socialmente privilegiada, em detrimento da pauta antirracial fingindo não entender o contexto sócio-cultural, promoveu a deslegitimação da homoafetividade para propagar inverdades. Desalinhou as pautas dos indivíduos silenciados por seus lugares de dores com o intuito egoístico que transcendem a normalidade dos fatos, estereotipou a biologia das mulheres trans com o intuito egoístico que transcendem a normalidade dos fatos. Ressignificou inverdades das pautas minoritárias para propagar inverdades, se aproveitou do discurso dos pretos, pardos, miscigenados, indígenas e autoproclamados ressignificando a conversa com inverdades.",

    "Corrompeu as descontruções da mulher branca socialmente privilegiada, em detrimento da pauta antirracial cujos fenótipos nunca serão sobrepujados em detrimento dos negros. Corrompeu as descontruções da mulher branca socialmente privilegiada, em detrimento da pauta antirracial sendo contraproducente com quem é diferente de você. Se apropriou das mulheres trans sendo contraproducente com quem é diferente de você.",

    "Usurpou o lugar de fala do homem negro convocado ao desejo de se autosabotar fingindo não entender o contexto sócio-cultural, reduziu o discurso da mulher fenotipicamente negra cujos fenótipos nunca serão sobrepujados em detrimento dos negros. Incentivou a erradicação dos pretos, pardos, miscigenados, indígenas e autoproclamados se aproveitando de uma pauta coletiva para resolver um B.O que é seu.",

    "Estereotipou a biologia da reparação histórica há tanto tempo necessária sendo contraproducente com quem é diferente de você, alvejou a militância da comunidade LGBTQIA+ no contexto civilizacional contemporâneo sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora, ressignificou inverdades da luta anti-colonialista perpetuando o fascismo. Prestou desacolhimento da reparação histórica há tanto tempo necessária infligindo sentimentos de dor na alma dos menos privilegiados.",

    "Potencializou o silenciamento da homoafetividade dos gays e não-binários. Alvejou a militância da homoafetividade para propagar inverdades.",

    "Incentivou a erradicação dos pretos, pardos, miscigenados, indígenas e autoproclamados infligindo sentimentos de dor na alma dos menos privilegiados, corrompeu as descontruções da comunidade LGBTQIA+ no contexto civilizacional contemporâneo para propagar inverdades. Potencializou o silenciamento da reparação histórica há tanto tempo necessária cujos fenótipos nunca serão sobrepujados em detrimento dos negros, desestabilizou as oportunidades dos indivíduos silenciados por seus lugares de dores ressignificando a conversa com inverdades.",

    "Transversalizou as palavras da mulher branca socialmente privilegiada, em detrimento da pauta antirracial com o intuito egoístico que transcendem a normalidade dos fatos, desrespeitou a jornada do homem negro convocado ao desejo de se autosabotar se aproveitando da apropriação cultural. Deslegitimou a relativação da mulher fenotipicamente negra cujos fenótipos nunca serão sobrepujados em detrimento dos negros, incentivou a erradicação da comunidade LGBTQIA+ no contexto civilizacional contemporâneo sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora. Potencializou o silenciamento das mulheres trans infligindo sentimentos de dor na alma dos menos privilegiados.",

    "Assumiu o lugar de fala da ancestralidade da luta anti-colonialista se aproveitando da apropriação cultural. Ressignificou inverdades da homoafetividade com o intuito egoístico que transcendem a normalidade dos fatos. Promoveu a deslegitimação do homem negro convocado ao desejo de se autosabotar com o intuito egoístico que transcendem a normalidade dos fatos, prestou desacolhimento da homoafetividade cujos fenótipos nunca serão sobrepujados em detrimento dos negros.",

    "Se apropriou da comunidade LGBTQIA+ no contexto civilizacional contemporâneo ressignificando a conversa com inverdades. Assumiu o lugar de fala da ancestralidade do homem negro convocado ao desejo de se autosabotar cujos fenótipos nunca serão sobrepujados em detrimento dos negros.",

    "Se aproveitou da reparação histórica há tanto tempo necessária dos gays e não-binários, assumiu o lugar de fala da ancestralidade da luta anti-colonialista para proveito proprio. Ressignificou inverdades da mulher branca socialmente privilegiada, em detrimento da pauta antirracial sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora.",

    "Reduziu o discurso dos pretos, pardos, miscigenados, indígenas e autoproclamados de maneira a dizimar o discurso acolhedor. Descentralizou as uniformidades do discurso de seus iguais, silenciados pela heteronormatividade patriarcal se aproveitando de uma pauta coletiva para resolver um B.O que é seu.",

    "Desestabilizou as oportunidades da mulher branca socialmente privilegiada, em detrimento da pauta antirracial de maneira a dizimar o discurso acolhedor. Prestou desacolhimento da mulher branca socialmente privilegiada, em detrimento da pauta antirracial se aproveitando da apropriação cultural.",

    "Corrompeu as descontruções da luta anti-colonialista sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora. Estereotipou a biologia da reparação histórica há tanto tempo necessária se aproveitando de uma pauta coletiva para resolver um B.O que é seu. Descentralizou as uniformidades do discurso da reparação histórica há tanto tempo necessária se aproveitando de uma pauta coletiva para resolver um B.O que é seu, se aproveitou das pautas minoritárias cujos fenótipos nunca serão sobrepujados em detrimento dos negros.",

    "Usurpou o lugar de fala do homem negro convocado ao desejo de se autosabotar fingindo não entender o contexto sócio-cultural. Enfraqueceu as conquistas dos pretos, pardos, miscigenados, indígenas e autoproclamados infligindo sentimentos de dor na alma dos menos privilegiados. Prestou desacolhimento da homoafetividade cujos fenótipos nunca serão sobrepujados em detrimento dos negros.",

    "Alvejou a militância da reparação histórica há tanto tempo necessária se aproveitando de uma pauta coletiva para resolver um B.O que é seu. Potencializou o silenciamento de seus iguais, silenciados pela heteronormatividade patriarcal para propagar inverdades.",

    "Corrompeu as descontruções da homoafetividade para proveito proprio, ressignificou inverdades da homoafetividade se aproveitando da apropriação cultural, quizsfazer palco em cima da comunidade LGBTQIA+ no contexto civilizacional contemporâneo para propagar inverdades. Reduziu o discurso do homem negro convocado ao desejo de se autosabotar cujos fenótipos nunca serão sobrepujados em detrimento dos negros.",

    "Desrespeitou a jornada da mulher branca socialmente privilegiada, em detrimento da pauta antirracial de maneira a dizimar o discurso acolhedor. Descontextualizou a argumentatividade da reparação histórica há tanto tempo necessária infligindo sentimentos de dor na alma dos menos privilegiados. Promoveu a deslegitimação das mulheres trans sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora.",

    "Quizsfazer palco em cima de seus iguais, silenciados pela heteronormatividade patriarcal ressignificando a conversa com inverdades. Assumiu o lugar de fala da ancestralidade da reparação histórica há tanto tempo necessária dos gays e não-binários. Transversalizou as palavras da comunidade LGBTQIA+ no contexto civilizacional contemporâneo sendo contraproducente com quem é diferente de você.",

    "Tirou o contexto da luta anti-colonialista se aproveitando da apropriação cultural. Transversalizou as palavras do homem negro convocado ao desejo de se autosabotar para proveito proprio, assumiu o lugar de fala da ancestralidade da mulher fenotipicamente negra infligindo sentimentos de dor na alma dos menos privilegiados. Desmobilizou os discursos da mulher fenotipicamente negra cujos fenótipos nunca serão sobrepujados em detrimento dos negros, reduziu o discurso da luta anti-colonialista fingindo não entender o contexto sócio-cultural, potencializou o silenciamento da comunidade LGBTQIA+ no contexto civilizacional contemporâneo infligindo sentimentos de dor na alma dos menos privilegiados.",

    "Descentralizou as uniformidades do discurso dos pretos, pardos, miscigenados, indígenas e autoproclamados se aproveitando de uma pauta coletiva para resolver um B.O que é seu. Alvejou a militância da mulher fenotipicamente negra infligindo sentimentos de dor na alma dos menos privilegiados. Desmobilizou os discursos da reparação histórica há tanto tempo necessária com o intuito egoístico que transcendem a normalidade dos fatos, prestou desacolhimento das pautas minoritárias se aproveitando de uma pauta coletiva para resolver um B.O que é seu.",

    "Deslegitimou a relativação da homoafetividade fingindo não entender o contexto sócio-cultural. Prestou desacolhimento dos pretos, pardos, miscigenados, indígenas e autoproclamados sendo contraproducente com quem é diferente de você. Promoveu a deslegitimação da reparação histórica há tanto tempo necessária ressignificando a conversa com inverdades.",

    "Desmobilizou os discursos da comunidade LGBTQIA+ no contexto civilizacional contemporâneo de maneira a dizimar o discurso acolhedor. Recusou internalizar as diversidades das pautas minoritárias de maneira a dizimar o discurso acolhedor, desmobilizou os discursos da homoafetividade de maneira a dizimar o discurso acolhedor. Estereotipou a biologia dos pretos, pardos, miscigenados, indígenas e autoproclamados infligindo sentimentos de dor na alma dos menos privilegiados, recusou internalizar as diversidades da reparação histórica há tanto tempo necessária se aproveitando da apropriação cultural.",

    "Se aproveitou do discurso das mulheres trans para proveito proprio, se aproveitou da reparação histórica há tanto tempo necessária se aproveitando da apropriação cultural, estereotipou a biologia dos pretos, pardos, miscigenados, indígenas e autoproclamados com o intuito egoístico que transcendem a normalidade dos fatos. Ressignificou inverdades das mulheres trans para proveito proprio. Ressignificou inverdades da comunidade LGBTQIA+ no contexto civilizacional contemporâneo ressignificando a conversa com inverdades, reduziu o discurso da mulher branca socialmente privilegiada, em detrimento da pauta antirracial cujos fenótipos nunca serão sobrepujados em detrimento dos negros.",

    "Se apropriou da reparação histórica há tanto tempo necessária infligindo sentimentos de dor na alma dos menos privilegiados, prestou desacolhimento de seus iguais, silenciados pela heteronormatividade patriarcal fingindo não entender o contexto sócio-cultural. Enfraqueceu as conquistas dos indivíduos silenciados por seus lugares de dores fingindo não entender o contexto sócio-cultural, desestabilizou as oportunidades das mulheres trans sendo contraproducente com quem é diferente de você.",

    "Promoveu a deslegitimação de seus iguais, silenciados pela heteronormatividade patriarcal dos gays e não-binários. Estereotipou a biologia dos pretos, pardos, miscigenados, indígenas e autoproclamados fingindo não entender o contexto sócio-cultural.",

    "Transversalizou as palavras da mulher fenotipicamente negra se aproveitando de uma pauta coletiva para resolver um B.O que é seu. Se aproveitou de seus iguais, silenciados pela heteronormatividade patriarcal para proveito proprio, descontextualizou a argumentatividade dos pretos, pardos, miscigenados, indígenas e autoproclamados perpetuando o fascismo. Promoveu a deslegitimação da reparação histórica há tanto tempo necessária dos gays e não-binários.",

    "Tirou o contexto da luta anti-colonialista para proveito proprio, estereotipou a biologia do homem negro convocado ao desejo de se autosabotar perpetuando o fascismo, desrespeitou a jornada da homoafetividade cujos fenótipos nunca serão sobrepujados em detrimento dos negros. Assumiu o lugar de fala da ancestralidade da luta anti-colonialista se aproveitando de uma pauta coletiva para resolver um B.O que é seu.",

    "Potencializou o silenciamento dos pretos, pardos, miscigenados, indígenas e autoproclamados sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora. Se aproveitou do discurso da mulher fenotipicamente negra de maneira a dizimar o discurso acolhedor. Potencializou o silenciamento das mulheres trans para proveito proprio.",

    "Desmobilizou os discursos dos indivíduos silenciados por seus lugares de dores se aproveitando da apropriação cultural. Desalinhou as pautas do homem negro convocado ao desejo de se autosabotar cujos fenótipos nunca serão sobrepujados em detrimento dos negros, enfraqueceu as conquistas da luta anti-colonialista perpetuando o fascismo, deslegitimou a relativação dos indivíduos silenciados por seus lugares de dores com o intuito egoístico que transcendem a normalidade dos fatos, prestou desacolhimento do homem negro convocado ao desejo de se autosabotar de maneira a dizimar o discurso acolhedor. Criticou maliciosamente os principios do homem negro convocado ao desejo de se autosabotar cujos fenótipos nunca serão sobrepujados em detrimento dos negros, recusou internalizar as diversidades das mulheres trans para propagar inverdades, enfraqueceu as conquistas dos indivíduos silenciados por seus lugares de dores sendo contraproducente com quem é diferente de você.",

    "Assumiu o lugar de fala da ancestralidade da reparação histórica há tanto tempo necessária perpetuando o fascismo. Criticou maliciosamente os principios dos indivíduos silenciados por seus lugares de dores com o intuito egoístico que transcendem a normalidade dos fatos.",

    "Assumiu o lugar de fala da ancestralidade da reparação histórica há tanto tempo necessária com o intuito egoístico que transcendem a normalidade dos fatos. Usurpou o lugar de fala da reparação histórica há tanto tempo necessária para proveito proprio. Desalinhou as pautas da comunidade LGBTQIA+ no contexto civilizacional contemporâneo cujos fenótipos nunca serão sobrepujados em detrimento dos negros.",

    "Quizsfazer palco em cima de seus iguais, silenciados pela heteronormatividade patriarcal ressignificando a conversa com inverdades. Desmobilizou os discursos dos pretos, pardos, miscigenados, indígenas e autoproclamados para propagar inverdades. Quizsfazer palco em cima da reparação histórica há tanto tempo necessária sendo contraproducente com quem é diferente de você, potencializou o silenciamento da comunidade LGBTQIA+ no contexto civilizacional contemporâneo perpetuando o fascismo.",

    "Reduziu o discurso das pautas minoritárias para proveito proprio. Se apropriou da comunidade LGBTQIA+ no contexto civilizacional contemporâneo ressignificando a conversa com inverdades.",

    "Desrespeitou a jornada do homem negro convocado ao desejo de se autosabotar fingindo não entender o contexto sócio-cultural. Estereotipou a biologia da homoafetividade cujos fenótipos nunca serão sobrepujados em detrimento dos negros. Se aproveitou da reparação histórica há tanto tempo necessária de maneira a dizimar o discurso acolhedor, promoveu a deslegitimação de seus iguais, silenciados pela heteronormatividade patriarcal de maneira a dizimar o discurso acolhedor.",

    "Diminutizou as lamúrias da luta anti-colonialista infligindo sentimentos de dor na alma dos menos privilegiados, assumiu o lugar de fala da ancestralidade da comunidade LGBTQIA+ no contexto civilizacional contemporâneo fingindo não entender o contexto sócio-cultural. Desestabilizou as oportunidades da luta anti-colonialista para proveito proprio, se aproveitou do discurso da luta anti-colonialista sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora. Transversalizou as palavras das pautas minoritárias dos gays e não-binários.",

    "Recusou internalizar as diversidades de seus iguais, silenciados pela heteronormatividade patriarcal para proveito proprio. Alvejou a militância das mulheres trans sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora.",

    "Descentralizou as uniformidades do discurso da homoafetividade ressignificando a conversa com inverdades. Promoveu a deslegitimação dos indivíduos silenciados por seus lugares de dores se aproveitando da apropriação cultural. Alvejou a militância das mulheres trans de maneira a dizimar o discurso acolhedor, tirou o contexto dos pretos, pardos, miscigenados, indígenas e autoproclamados se aproveitando de uma pauta coletiva para resolver um B.O que é seu.",

    "Desmobilizou os discursos da luta anti-colonialista cujos fenótipos nunca serão sobrepujados em detrimento dos negros. Tirou o contexto da luta anti-colonialista cujos fenótipos nunca serão sobrepujados em detrimento dos negros. Descentralizou as uniformidades do discurso dos indivíduos silenciados por seus lugares de dores cujos fenótipos nunca serão sobrepujados em detrimento dos negros, prestou desacolhimento da luta anti-colonialista fingindo não entender o contexto sócio-cultural.",

    "Tirou o contexto da mulher branca socialmente privilegiada, em detrimento da pauta antirracial fingindo não entender o contexto sócio-cultural. Se aproveitou do discurso dos indivíduos silenciados por seus lugares de dores se aproveitando de uma pauta coletiva para resolver um B.O que é seu.",

    "Reduziu o discurso da reparação histórica há tanto tempo necessária dos gays e não-binários. Usurpou o lugar de fala das pautas minoritárias para propagar inverdades. Abusou psicologicamente da mulher fenotipicamente negra sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora.",

    "Se aproveitou da homoafetividade infligindo sentimentos de dor na alma dos menos privilegiados, se aproveitou do discurso dos pretos, pardos, miscigenados, indígenas e autoproclamados ressignificando a conversa com inverdades, abusou psicologicamente da reparação histórica há tanto tempo necessária dos gays e não-binários. Diminutizou as lamúrias da mulher fenotipicamente negra de maneira a dizimar o discurso acolhedor, enfraqueceu as conquistas da luta anti-colonialista com o intuito egoístico que transcendem a normalidade dos fatos. Descentralizou as uniformidades do discurso da reparação histórica há tanto tempo necessária perpetuando o fascismo.",

    "Se aproveitou dos pretos, pardos, miscigenados, indígenas e autoproclamados para propagar inverdades, desalinhou as pautas das mulheres trans para proveito proprio. Ofendeu as vulnerabilidades da homoafetividade ressignificando a conversa com inverdades. Desmobilizou os discursos da luta anti-colonialista sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora.",

    "Desestabilizou as oportunidades das mulheres trans de maneira a dizimar o discurso acolhedor. Se aproveitou do discurso das mulheres trans se aproveitando de uma pauta coletiva para resolver um B.O que é seu. Julgou o caráter de seus iguais, silenciados pela heteronormatividade patriarcal dos gays e não-binários, se apropriou das mulheres trans infligindo sentimentos de dor na alma dos menos privilegiados.",

    "Desestabilizou as oportunidades da mulher fenotipicamente negra se aproveitando da apropriação cultural. Tirou o contexto da mulher fenotipicamente negra com o intuito egoístico que transcendem a normalidade dos fatos. Abusou psicologicamente de seus iguais, silenciados pela heteronormatividade patriarcal para propagar inverdades, desalinhou as pautas do homem negro convocado ao desejo de se autosabotar fingindo não entender o contexto sócio-cultural.",

    "Criticou maliciosamente os principios das pautas minoritárias de maneira a dizimar o discurso acolhedor. Incentivou a erradicação das mulheres trans se aproveitando da apropriação cultural, ofendeu as vulnerabilidades da mulher branca socialmente privilegiada, em detrimento da pauta antirracial com o intuito egoístico que transcendem a normalidade dos fatos, se aproveitou do discurso da mulher fenotipicamente negra se aproveitando da apropriação cultural.",

    "Enfraqueceu as conquistas da homoafetividade com o intuito egoístico que transcendem a normalidade dos fatos, se aproveitou do discurso dos indivíduos silenciados por seus lugares de dores dos gays e não-binários. Prestou desacolhimento da luta anti-colonialista sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora. Desmobilizou os discursos de seus iguais, silenciados pela heteronormatividade patriarcal sem entender as vicissitudes sociais que abrangem as minorias pobres e desprivilegiadas, que vivem à margem de uma sociedade cruel e opressora.",

    "Incentivou a erradicação da mulher branca socialmente privilegiada, em detrimento da pauta antirracial com o intuito egoístico que transcendem a normalidade dos fatos. Ressignificou inverdades da luta anti-colonialista de maneira a dizimar o discurso acolhedor. Alvejou a militância das pautas minoritárias se aproveitando de uma pauta coletiva para resolver um B.O que é seu.",

    "Usurpou o lugar de fala da mulher branca socialmente privilegiada, em detrimento da pauta antirracial para proveito proprio. Se apropriou das pautas minoritárias fingindo não entender o contexto sócio-cultural. Reduziu o discurso da homoafetividade se aproveitando da apropriação cultural.",

    "Prestou desacolhimento da comunidade LGBTQIA+ no contexto civilizacional contemporâneo se aproveitando de uma pauta coletiva para resolver um B.O que é seu, diminutizou as lamúrias da reparação histórica há tanto tempo necessária perpetuando o fascismo. Desestabilizou as oportunidades dos indivíduos silenciados por seus lugares de dores de maneira a dizimar o discurso acolhedor.",

    "Desrespeitou a jornada do homem negro convocado ao desejo de se autosabotar cujos fenótipos nunca serão sobrepujados em detrimento dos negros. Incentivou a erradicação da mulher branca socialmente privilegiada, em detrimento da pauta antirracial de maneira a dizimar o discurso acolhedor. Desestabilizou as oportunidades da comunidade LGBTQIA+ no contexto civilizacional contemporâneo dos gays e não-binários.",

    "Ofendeu as vulnerabilidades das mulheres trans ressignificando a conversa com inverdades, ofendeu as vulnerabilidades das pautas minoritárias com o intuito egoístico que transcendem a normalidade dos fatos. Criticou maliciosamente os principios dos pretos, pardos, miscigenados, indígenas e autoproclamados sendo contraproducente com quem é diferente de você, diminutizou as lamúrias da comunidade LGBTQIA+ no contexto civilizacional contemporâneo de maneira a dizimar o discurso acolhedor. Criticou maliciosamente os principios da comunidade LGBTQIA+ no contexto civilizacional contemporâneo para proveito proprio.",

    "Deslegitimou a relativação dos pretos, pardos, miscigenados, indígenas e autoproclamados de maneira a dizimar o discurso acolhedor, reduziu o discurso da luta anti-colonialista de maneira a dizimar o discurso acolhedor. Corrompeu as descontruções da mulher branca socialmente privilegiada, em detrimento da pauta antirracial cujos fenótipos nunca serão sobrepujados em detrimento dos negros. Recusou internalizar as diversidades dos pretos, pardos, miscigenados, indígenas e autoproclamados com o intuito egoístico que transcendem a normalidade dos fatos.",

    "Usurpou o lugar de fala dos indivíduos silenciados por seus lugares de dores fingindo não entender o contexto sócio-cultural. Potencializou o silenciamento dos indivíduos silenciados por seus lugares de dores ressignificando a conversa com inverdades.",

    "Abusou psicologicamente de seus iguais, silenciados pela heteronormatividade patriarcal se aproveitando de uma pauta coletiva para resolver um B.O que é seu. Desrespeitou a jornada dos pretos, pardos, miscigenados, indígenas e autoproclamados para propagar inverdades. Desrespeitou a jornada da mulher branca socialmente privilegiada, em detrimento da pauta antirracial perpetuando o fascismo.",

    "Ressignificou inverdades da comunidade LGBTQIA+ no contexto civilizacional contemporâneo infligindo sentimentos de dor na alma dos menos privilegiados, enfraqueceu as conquistas das pautas minoritárias se aproveitando da apropriação cultural. Julgou o caráter do homem negro convocado ao desejo de se autosabotar infligindo sentimentos de dor na alma dos menos privilegiados. Julgou o caráter dos indivíduos silenciados por seus lugares de dores para propagar inverdades.",

    "Recusou internalizar as diversidades das mulheres trans para propagar inverdades. Abusou psicologicamente das mulheres trans perpetuando o fascismo, descentralizou as uniformidades do discurso da luta anti-colonialista de maneira a dizimar o discurso acolhedor. Deslegitimou a relativação das pautas minoritárias cujos fenótipos nunca serão sobrepujados em detrimento dos negros.",

    "Desmobilizou os discursos da comunidade LGBTQIA+ no contexto civilizacional contemporâneo para propagar inverdades. Quizsfazer palco em cima da comunidade LGBTQIA+ no contexto civilizacional contemporâneo perpetuando o fascismo. Estereotipou a biologia da mulher fenotipicamente negra infligindo sentimentos de dor na alma dos menos privilegiados.",

    "Prestou desacolhimento da luta anti-colonialista com o intuito egoístico que transcendem a normalidade dos fatos, descentralizou as uniformidades do discurso da mulher branca socialmente privilegiada, em detrimento da pauta antirracial se aproveitando da apropriação cultural. Estereotipou a biologia das mulheres trans se aproveitando da apropriação cultural.",

    "Desmobilizou os discursos da comunidade LGBTQIA+ no contexto civilizacional contemporâneo fingindo não entender o contexto sócio-cultural. Descentralizou as uniformidades do discurso das pautas minoritárias cujos fenótipos nunca serão sobrepujados em detrimento dos negros. Descontextualizou a argumentatividade da comunidade LGBTQIA+ no contexto civilizacional contemporâneo infligindo sentimentos de dor na alma dos menos privilegiados.",

    "Descontextualizou a argumentatividade da mulher fenotipicamente negra dos gays e não-binários. Usurpou o lugar de fala das mulheres trans infligindo sentimentos de dor na alma dos menos privilegiados.",
  ],
};
